## ARRAY SLICING

In [1]:
import numpy as np
a=np.random.randint(1,15,(6,5))
print(a)

[[ 4 14  2  1  8]
 [11 11  8 13  3]
 [ 2  1  4 11 13]
 [ 3  3 12  9  4]
 [ 7 12 10 10 12]
 [12  1  2  3  4]]


In [8]:
a[:,0::4]


array([[ 4,  8],
       [11,  3],
       [ 2, 13],
       [ 3,  4],
       [ 7, 12],
       [12,  4]])

In [62]:
a[1:3]

array([[ 6,  1, 14, 12,  6],
       [ 4, 12,  3, 14,  6]])

In [58]:
a[3,2]

5

In [59]:
a[2,:]

array([ 4, 12,  3, 14,  6])

In [60]:
a[::2,::2]

array([[10, 11,  5],
       [ 4,  3,  6],
       [ 7,  5, 14]])

In [13]:
print(a)
a[::-1]

[[ 9  2  9 11  4]
 [ 8  9  8 13 14]
 [13  3 12 13  2]
 [ 3 10  2  3  4]
 [ 6  5  5  1 12]
 [11 14  4  3  2]]


array([[11, 14,  4,  3,  2],
       [ 6,  5,  5,  1, 12],
       [ 3, 10,  2,  3,  4],
       [13,  3, 12, 13,  2],
       [ 8,  9,  8, 13, 14],
       [ 9,  2,  9, 11,  4]])

In [14]:
print(a)
a[::-1,::-1]

[[ 9  2  9 11  4]
 [ 8  9  8 13 14]
 [13  3 12 13  2]
 [ 3 10  2  3  4]
 [ 6  5  5  1 12]
 [11 14  4  3  2]]


array([[ 2,  3,  4, 14, 11],
       [12,  1,  5,  5,  6],
       [ 4,  3,  2, 10,  3],
       [ 2, 13, 12,  3, 13],
       [14, 13,  8,  9,  8],
       [ 4, 11,  9,  2,  9]])

In [17]:
a[:,::-1]

array([[ 4, 11,  9,  2,  9],
       [14, 13,  8,  9,  8],
       [ 2, 13, 12,  3, 13],
       [ 4,  3,  2, 10,  3],
       [12,  1,  5,  5,  6],
       [ 2,  3,  4, 14, 11]])

In [18]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14])

In [20]:
print(a)
np.sort(a)


[[ 9  2  9 11  4]
 [ 8  9  8 13 14]
 [13  3 12 13  2]
 [ 3 10  2  3  4]
 [ 6  5  5  1 12]
 [11 14  4  3  2]]


array([[ 2,  4,  9,  9, 11],
       [ 8,  8,  9, 13, 14],
       [ 2,  3, 12, 13, 13],
       [ 2,  3,  3,  4, 10],
       [ 1,  5,  5,  6, 12],
       [ 2,  3,  4, 11, 14]])

In [22]:
print(a)
np.sort(a,axis=0)

[[ 9  2  9 11  4]
 [ 8  9  8 13 14]
 [13  3 12 13  2]
 [ 3 10  2  3  4]
 [ 6  5  5  1 12]
 [11 14  4  3  2]]


array([[ 3,  2,  2,  1,  2],
       [ 6,  3,  4,  3,  2],
       [ 8,  5,  5,  3,  4],
       [ 9,  9,  8, 11,  4],
       [11, 10,  9, 13, 12],
       [13, 14, 12, 13, 14]])

In [24]:
print(a)
np.sort(a,axis=1)


[[ 9  2  9 11  4]
 [ 8  9  8 13 14]
 [13  3 12 13  2]
 [ 3 10  2  3  4]
 [ 6  5  5  1 12]
 [11 14  4  3  2]]


array([[ 2,  4,  9,  9, 11],
       [ 8,  8,  9, 13, 14],
       [ 2,  3, 12, 13, 13],
       [ 2,  3,  3,  4, 10],
       [ 1,  5,  5,  6, 12],
       [ 2,  3,  4, 11, 14]])

In [25]:
b=a.flatten()
b

array([ 9,  2,  9, 11,  4,  8,  9,  8, 13, 14, 13,  3, 12, 13,  2,  3, 10,
        2,  3,  4,  6,  5,  5,  1, 12, 11, 14,  4,  3,  2])

In [26]:
a=np.sort(b)

In [27]:
a

array([ 1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  5,  5,  6,  8,  8,
        9,  9,  9, 10, 11, 11, 12, 12, 13, 13, 13, 14, 14])

In [28]:
a=a.reshape(6,5)
a

array([[ 1,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  4],
       [ 4,  4,  5,  5,  6],
       [ 8,  8,  9,  9,  9],
       [10, 11, 11, 12, 12],
       [13, 13, 13, 14, 14]])

In [29]:
a= np.arange(1,11)
b=np.arange(11,21)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [30]:

np.append(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
print(a)
print(b)
np.append(a,b,axis=0)


[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a= np.arange(1,11).reshape(2,5)
b=np.arange(11,21).reshape(2,5)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
np.append(a,b)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
print(a)
print(b)
np.append(a,b,axis=0)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
print(a)
print(b)
np.append(a,b,axis=1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [36]:
a = np.random.randint(1,11,(2,5))
b = np.random.randint(1,11,(2,5))
print(a)
print(b)
c= a-b
print(c)

[[10  8 10  2  5]
 [ 5 10 10  4  5]]
[[ 4  6 10  2  8]
 [ 6  7  4  4  1]]
[[ 6  2  0  0 -3]
 [-1  3  6  0  4]]


In [38]:
c[c>0]

array([6, 2, 3, 6, 4])

In [40]:
c[c<0]

array([-3, -1])

In [41]:
c[c<0]=10


In [42]:
c

array([[ 6,  2,  0,  0, 10],
       [10,  3,  6,  0,  4]])

In [43]:
b

array([[ 4,  6, 10,  2,  8],
       [ 6,  7,  4,  4,  1]])

In [44]:
b[b%2==0]

array([ 4,  6, 10,  2,  8,  6,  4,  4])

In [45]:
b[b%2==1]

array([7, 1])