In [2]:
import numpy as np


## Que1

In [6]:
a= np.random.randint(1,3,(1,3))
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.data)


[[1 1 1]]
2
3
(1, 3)
4
int32


In [7]:
a= np.random.randint(1,6,(2,3))
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.data)

[[5 2 2]
 [4 3 4]]
2
6
(2, 3)
4
int32


In [8]:
a= np.random.randint(1,6,(3,3))
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.data)

[[1 4 3]
 [5 2 5]
 [5 2 4]]
2
9
(3, 3)
4
int32


## Que 2

In [14]:
a= np.empty((3,5),dtype=int)
print(a)


[[3801155 5570652 6619251 7536754 4915292]
 [5374017 4784212 6029387 7340097 4456560]
 [7602273 6029409 7274572 6357091 6029420]]


In [6]:
a=np.full((5,3),5,dtype=int)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [8]:
a= np.zeros((5,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
a=np.ones((5,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## que 3

In [27]:
a=np.random.randint(14,40,(5,5))
print(a)



[[21 16 34 14 20]
 [28 16 29 16 38]
 [23 26 35 29 23]
 [28 18 32 26 25]
 [27 18 23 27 17]]


## que 4

In [33]:
a=np.random.randint(1,40,(8,5))
print(a)

[[ 7 34 19 13 20]
 [18 33 19  5 15]
 [27 11  2  7 35]
 [ 3 23 12 18 23]
 [ 9  8 33 11 25]
 [35 32 37 31 25]
 [19 31 38 10 32]
 [ 8  3 33 22 26]]


## que 5

In [35]:
a.resize(4,10,refcheck=False)
a

array([[ 7, 34, 19, 13, 20, 18, 33, 19,  5, 15],
       [27, 11,  2,  7, 35,  3, 23, 12, 18, 23],
       [ 9,  8, 33, 11, 25, 35, 32, 37, 31, 25],
       [19, 31, 38, 10, 32,  8,  3, 33, 22, 26]])

## que6

In [1]:
a
a[0:3,0:4]
a[0:3,4:5]
a[2:4]
a[::,3:6]

NameError: name 'a' is not defined

## que 7

In [61]:
b=a.flatten()

b[b%2==1]

array([ 7, 19, 13, 33, 19,  5, 15, 27, 11,  7, 35,  3, 23, 23,  9, 33, 11,
       25, 35, 37, 31, 25, 19, 31,  3, 33])

## que 8

In [63]:
b=a.flatten()

b[b%2==0]=-1
b

array([ 7, -1, 19, 13, -1, -1, 33, 19,  5, 15, 27, 11, -1,  7, 35,  3, 23,
       -1, -1, 23,  9, -1, 33, 11, 25, 35, -1, 37, 31, 25, 19, 31, -1, -1,
       -1, -1,  3, 33, -1, -1])

## que 9

In [67]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
np.append(a,b)

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

# que 10

In [82]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

b=a.reshape(2,8)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

## que 11

In [100]:
a = np.random.randint(13,40,(2,6))
np.sort(a,axis=1)


array([[20, 22, 27, 28, 35, 38],
       [14, 14, 18, 23, 23, 29]])

In [108]:
np.sort(a,axis)

NameError: name 'axis' is not defined

## que 12 

In [109]:
b=np.random.randint(1,15,(5,3))
print(b)
print(b+4)
print(b*2)
print(b-3)
print(b//2)

[[ 9  8  1]
 [ 8  7 12]
 [ 4  8 14]
 [ 7 13 13]
 [ 4 11  8]]
[[13 12  5]
 [12 11 16]
 [ 8 12 18]
 [11 17 17]
 [ 8 15 12]]
[[18 16  2]
 [16 14 24]
 [ 8 16 28]
 [14 26 26]
 [ 8 22 16]]
[[ 6  5 -2]
 [ 5  4  9]
 [ 1  5 11]
 [ 4 10 10]
 [ 1  8  5]]
[[4 4 0]
 [4 3 6]
 [2 4 7]
 [3 6 6]
 [2 5 4]]


## que 13

In [112]:
b=np.random.randint(1,9,(3,3))
c=np.random.randint(1,9,(3,3))
print(b)
print(c)

print(b+c)
print(b-c)
print(b*c)
print(b.dot(c))
print(b.sum(axis=0))
print(b.min(axis=0))
print(c.max(axis=0))

[[5 8 4]
 [6 5 4]
 [3 2 7]]
[[3 2 1]
 [8 3 3]
 [5 2 6]]
[[ 8 10  5]
 [14  8  7]
 [ 8  4 13]]
[[ 2  6  3]
 [-2  2  1]
 [-2  0  1]]
[[15 16  4]
 [48 15 12]
 [15  4 42]]
[[99 42 53]
 [78 35 45]
 [60 26 51]]
[14 15 15]
[3 2 4]
[8 3 6]
