In [2]:
import numpy as np
print(np.__version__)

1.23.5


In [3]:
lst=[[[1,2,3,4,5],[10,20,30,40,50]],[[11,21,31,41,51],[110,120,130,140,150]]]
a=np.array(lst)
print(a)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]]

 [[ 11  21  31  41  51]
  [110 120 130 140 150]]]


In [4]:
print(type(a))
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.data)


<class 'numpy.ndarray'>
3
20
(2, 2, 5)
4
int32


In [5]:
a= np.zeros(3,dtype=int)
print(a)

[0 0 0]


In [6]:

a= np.zeros((2,5,4),dtype=int)
print(a)


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [7]:
a= np.empty((2,5,4),dtype=int)
print(a)

[[[4128860 6029375 3801155 5570652]
  [6619251 7536754 4915292 5374017]
  [4784212 6029387 7209057 6488161]
  [7209071 6357092 6029363 6881388]
  [6029410 6881395 6619252 7340077]]

 [[6488161 6357099 6619239 6029427]
  [7667822 7340141 6029433 7274608]
  [7929964 7274606 6881389 7077985]
  [7340124 7077999 7209081 7143535]
  [6357097 3014764 7929968 7340032]]]


In [8]:
a= np.empty((2,5,4),dtype=int)
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [9]:
a= np.empty((2,5,4),dtype=int)
print(a)

[[[4128860 6029375 3801155 5570652]
  [6619251 7536754 4915292 5374017]
  [4784212 6029387 7209057 6488161]
  [7209071 6357092 6029363 6881388]
  [6029410 6881395 6619252 7340077]]

 [[6488161 6357099 6619239 6029427]
  [7667822 7340141 6029433 7274608]
  [7929964 7274606 6881389 7077985]
  [7340124 7077999 7209081 7143535]
  [6357097 3014764 7929968 7340032]]]


In [10]:
a= np.identity(5,dtype=int)
print(a)
print(type(a))
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)
print(a.data)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
<class 'numpy.ndarray'>
2
25
(5, 5)
4
int32


In [11]:

a= np.full(5,4,dtype=int)
print(a)


[4 4 4 4 4]


In [12]:

a= np.full((5,6),4,dtype=int)
print(a)


[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [13]:
a= np.full((5,2,3),8,dtype=int)
print(a)

[[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]]


In [49]:
a= np.eye(5,k=0,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:


a= np.eye(5,4,k=-1,dtype=int)
print(a)


[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [16]:
a= np.random.random((5,3))
print(a)


[[0.62383236 0.62958136 0.16753704]
 [0.1550628  0.73208934 0.08868597]
 [0.71764478 0.58905894 0.99373721]
 [0.97500454 0.44862673 0.26519071]
 [0.51644744 0.65637852 0.776246  ]]


In [17]:
a= np.random.randint(1,10,5)
print(a)

[8 2 7 2 8]


In [18]:
a= np.random.randint(1,10,(2,5))
print(a)


[[5 5 3 8 5]
 [6 6 2 2 5]]


In [19]:
a= np.random.randint(1,20,(2,5,6))
print(a)


[[[17 13 18  7  2  3]
  [10 17  1  3  5 12]
  [ 2  8  5  7 10  2]
  [12  9  6 17  4  7]
  [ 4  8  8  3  6  2]]

 [[ 8 12  6  5 12 10]
  [ 7 19 16 11  2  3]
  [ 9  6  4 13 10  1]
  [13 19 18 12  3 10]
  [ 7 11 19  3  7  5]]]


In [20]:
print(a)

[[[17 13 18  7  2  3]
  [10 17  1  3  5 12]
  [ 2  8  5  7 10  2]
  [12  9  6 17  4  7]
  [ 4  8  8  3  6  2]]

 [[ 8 12  6  5 12 10]
  [ 7 19 16 11  2  3]
  [ 9  6  4 13 10  1]
  [13 19 18 12  3 10]
  [ 7 11 19  3  7  5]]]


In [21]:
a= np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [22]:
a= np.random.randint(1,10,(2,5))
print(a)


[[6 7 7 2 7]
 [1 8 1 1 2]]


In [23]:
a= np.arange(1,100,2)
print(a)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [24]:
a= np.arange(1,10).reshape(3,3)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a= np.arange(1,13).reshape(3,2,2)
print(a)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [26]:
a=np.random.randint(1,13,(3,4))

In [27]:
a

array([[ 8,  2,  5,  1],
       [ 6,  6,  1,  3],
       [ 8,  2,  5, 10]])

In [28]:
a.resize(3,3,refcheck=False)
print(a)

[[8 2 5]
 [1 6 6]
 [1 3 8]]


In [29]:
b=a.flatten()
b

array([8, 2, 5, 1, 6, 6, 1, 3, 8])

In [30]:

a=np.random.randint(1,13,(3,4))
a

array([[ 2,  6,  8,  8],
       [ 3,  7, 11,  1],
       [11,  1, 11,  3]])

In [46]:
a=a.reshape(-1)
print(a)


[5 8 2 3 5 4 6 6 4]


In [32]:
a= np.arange(1,5).reshape(2,2)
print(a)


[[1 2]
 [3 4]]


In [33]:
a+2

array([[3, 4],
       [5, 6]])

In [34]:
a*3

array([[ 3,  6],
       [ 9, 12]])

In [35]:
a= np.random.randint(1,9,(3,3))
b=np.random.randint(1,9,(3,3))
print(a)
print(b)


[[7 5 8]
 [6 1 6]
 [7 7 5]]
[[5 5 4]
 [4 6 5]
 [6 2 3]]


In [36]:
a+b

array([[12, 10, 12],
       [10,  7, 11],
       [13,  9,  8]])

In [37]:
a-b

array([[ 2,  0,  4],
       [ 2, -5,  1],
       [ 1,  5,  2]])

In [38]:
a//b

array([[1, 1, 2],
       [1, 0, 1],
       [1, 3, 1]])

In [39]:
a= np.random.randint(1,9,(3,3))
print(a)

[[5 8 2]
 [3 5 4]
 [6 6 4]]


In [40]:
print(a.sum())
print(a.min())
print(a.max())

43
2
8


In [41]:
print(a)
print(a.sum(axis=0))
print(a.min(axis=0))
print(a.max(axis=0))

[[5 8 2]
 [3 5 4]
 [6 6 4]]
[14 19 10]
[3 5 2]
[6 8 4]


In [42]:
print(a)
print(a.sum(axis=1))
print(a.min(axis=1))
print(a.max(axis=1))

[[5 8 2]
 [3 5 4]
 [6 6 4]]
[15 12 16]
[2 3 4]
[8 5 6]


In [43]:
a


array([[5, 8, 2],
       [3, 5, 4],
       [6, 6, 4]])

In [44]:
a.T  #transpose of matrix

array([[5, 3, 6],
       [8, 5, 6],
       [2, 4, 4]])

In [45]:
a.dot(b)  #matrics Multipication

array([[69, 77, 66],
       [59, 53, 49],
       [78, 74, 66]])